import streamlit as st
import pandas as pd
import joblib
from huggingface_hub import hf_hub_download

st.set_page_config(
    page_title="MediScan AI | Predictor",
    page_icon="M",
    layout="wide"
)

st.markdown(
    """
    <style>
    .stApp {
        background-color: #0B1117;
        color: #F8FAFC;
    }

    .page-title {
        font-size: 42px;
        font-weight: 800;
        color: #F8FAFC;
        margin-bottom: 10px;
    }

    .subtitle {
        font-size: 17px;
        color: #CBD5E1;
        margin-bottom: 30px;
    }

    .result-card {
        padding: 30px;
        border-radius: 20px;
        background: linear-gradient(135deg, #0F766E, #2563EB);
        color: white;
        margin-top: 25px;
    }

    .warning-box {
        padding: 18px;
        border-radius: 14px;
        background-color: #132F4C;
        color: #BFDBFE;
        margin-top: 20px;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.markdown('<div class="page-title">Drug Interaction Predictor</div>', unsafe_allow_html=True)

st.markdown(
    """
    <div class="subtitle">
    Select two drugs and predict the possible drug-drug interaction type using the trained Random Forest model.
    </div>
    """,
    unsafe_allow_html=True
)

@st.cache_data
def load_dataset():
    return pd.read_csv("data/processed/cleaned_DDI_data.csv")

@st.cache_resource
def load_model_and_encoders():
    from huggingface_hub import hf_hub_download
import joblib

REPO_ID = "thishan2004/mediscan-ai-model"

@st.cache_resource
def load_model_and_encoders():

    model_path = hf_hub_download(
        repo_id=REPO_ID,
        filename="best_model.pkl"
    )

    drug_encoder_path = hf_hub_download(
        repo_id=REPO_ID,
        filename="drug_encoder.pkl"
    )

    target_encoder_path = hf_hub_download(
        repo_id=REPO_ID,
        filename="target_encoder.pkl"
    )

    model = joblib.load(model_path)
    drug_encoder = joblib.load(drug_encoder_path)
    target_encoder = joblib.load(target_encoder_path)

    return model, drug_encoder, target_encoder
    return model, drug_encoder, target_encoder

df = load_dataset()
model, drug_encoder, target_encoder = load_model_and_encoders()

drug_list = sorted(
    pd.concat([
        df["drug1_name"],
        df["drug2_name"]
    ]).unique()
)

col1, col2 = st.columns(2)

with col1:
    drug1 = st.selectbox(
        "Select First Drug",
        drug_list
    )

with col2:
    drug2 = st.selectbox(
        "Select Second Drug",
        drug_list
    )

if st.button("Predict Interaction", use_container_width=True):

    if drug1 == drug2:
        st.warning("Please select two different drugs.")
    else:
        drug1_encoded = drug_encoder.transform([drug1])[0]
        drug2_encoded = drug_encoder.transform([drug2])[0]

        input_data = pd.DataFrame({
            "drug1_name": [drug1_encoded],
            "drug2_name": [drug2_encoded]
        })

        prediction = model.predict(input_data)[0]

        interaction_type = target_encoder.inverse_transform([prediction])[0]

        st.markdown(
            f"""
            <div class="result-card">
                <h2>Predicted Interaction Type</h2>
                <h3>{interaction_type}</h3>
                <p><strong>Drug Pair:</strong> {drug1} + {drug2}</p>
            </div>
            """,
            unsafe_allow_html=True
        )

        st.markdown(
            """
            <div class="warning-box">
                <strong>Important:</strong> This prediction is generated by a machine learning model trained on the DrugBank DDI dataset.
                It is intended only for educational and research purposes.
            </div>
            """,
            unsafe_allow_html=True
        )